### ISSUE TITLE
SpamService incorrectly matches URLs

### ISSUE THREAD

**Issue by MercurialPony** [Manechat/izzy-moonbot#400]
While working on URL sanitization in #397 I found that the URL regex in SpamService works incorrectly. Upon finding a valid URL it seems to match everything after it until the end of the line.

https://github.com/Manechat/izzy-moonbot/blob/d5d7a2539892c2200fc30f18162b6cf6bca50bd3/Izzy-Moonbot/Service/SpamService.cs#L45-L46

We could probably just use the regex I ended up using in my PR (it seems to work and it's from a highly upvoted SO post :p).

https://github.com/Manechat/izzy-moonbot/blob/d5d7a2539892c2200fc30f18162b6cf6bca50bd3/Izzy-Moonbot/Modules/QuotesModule.cs#L58

Ideally we would extract it so it can be shared between SpamService, QuotesModule and any other components. I'm just not sure about the best way to go about it yet.

**Comment by MercurialPony** [comment]
Though it's also worth noting the quote regex has positive lookaheads and lookbehinds for angle brackets, which might make extracting it a bit more annoying

**Comment by Ixrec** [comment]
Turns out it's not annoying at all: the current SpamService code is using two separate regexes and then doing its own nested loop stuff to figure out if exactly one of the two regexes matched the same part of the string to decide that the url will indeed unfurl. So (despite the meme about regexes) using the lookaround regex to make all that extra code go away makes for a far simpler and more readable implementation.
